name: Main

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: sestrella
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: ${{ github.ref_name != 'main' }}
      - run: nix build

  template:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - run: nix profile add nixpkgs#devenv
      - run: sed -i 's/github:sestrella\/auto-commit-msg/github:sestrella\/auto-commit-msg?ref=${{ github.sha }}/g' templates/default/devenv.yaml
      - run: echo "tmpdir=$(mktemp -d)" >> "$GITHUB_OUTPUT"
        id: mktemp
      - run: git init
        working-directory: ${{ steps.mktemp.outputs.tmpdir }}
      - run: nix flake init -t ${{ github.workspace }}
        working-directory: ${{ steps.mktemp.outputs.tmpdir }}
      - run: devenv test
        working-directory: ${{ steps.mktemp.outputs.tmpdir }}
      - run: cat .pre-commit-config.yaml
        working-directory: ${{ steps.mktemp.outputs.tmpdir }}

  release:
    runs-on: ubuntu-latest
    # needs: [build, template]
    strategy:
      matrix:
        goos:
          # - darwin
          - linux
        goarch:
          - amd64
          - arm64
      fail-fast: true
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: 1.25
      - run: go build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
      - run: file autocommitmsg
      - run: ldd autocommitmsg
