name: Main

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: sestrella
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: ${{ github.ref_name != 'main' }}
      - run: nix build

  template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - run: nix profile install nixpkgs#devenv
      - run: sed -i 's/github:sestrella\/auto-commit-msg/github:sestrella\/auto-commit-msg?ref=${{ github.sha }}/g' templates/default/devenv.nix
      - run: echo "tmpdir=$(mktemp -d)" >> "$GITHUB_OUTPUT"
        id: mktemp
      - run: nix flake init -t ${{ github.workspace }}#${{ matrix.template.name }}
        working-directory: ${{ steps.mktemp.outputs.tmpdir }}
      - run: devenv shell -- cat .pre-commit-config.yaml
        working-directory: ${{ steps.mktemp.outputs.tmpdir }}
